# https://taskfile.dev
version: '3'

vars:
  DIST_DIR: dist
  SERVER_DIR: server
  CLIENT_DIR: client-react
  MODULE_DIR: foundry-module
  DESKTOP_DIR: desktop
  DOCS_DIR: docs
  # Go bin path for wails CLI
  WAILS: '{{.GOPATH | default (env "GOPATH") | default "~/go"}}/bin/wails'
  # Foundry data path - override with FOUNDRY_DATA env var
  FOUNDRY_DATA: '{{.FOUNDRY_DATA | default "/Users/sphinizy/foundrydata/Data"}}'

tasks:
  # ================================
  # Default & Aggregate Tasks
  # ================================

  default:
    desc: Build everything (client, server, module)
    deps: [build:server, build:module]

  # ================================
  # Client (React)
  # ================================

  install:client:
    desc: Install client npm dependencies
    dir: '{{.CLIENT_DIR}}'
    cmds:
      - npm install
    sources:
      - '{{.CLIENT_DIR}}/package.json'
      - '{{.CLIENT_DIR}}/package-lock.json'
    generates:
      - '{{.CLIENT_DIR}}/node_modules/.package-lock.json'

  build:client:
    desc: Build React client and copy to server/public
    dir: '{{.CLIENT_DIR}}'
    deps: [install:client]
    cmds:
      - npm run build
      - rm -rf ../{{.SERVER_DIR}}/public/*
      - cp -r dist/* ../{{.SERVER_DIR}}/public/
    sources:
      - '{{.CLIENT_DIR}}/src/**/*'
      - '{{.CLIENT_DIR}}/index.html'
      - '{{.CLIENT_DIR}}/vite.config.ts'
      - '{{.CLIENT_DIR}}/tsconfig*.json'
    generates:
      - '{{.SERVER_DIR}}/public/**/*'

  dev:client:
    desc: Run client dev server with HMR
    dir: '{{.CLIENT_DIR}}'
    deps: [install:client]
    cmds:
      - npm run dev

  # ================================
  # Server (Go Relay)
  # ================================

  build:server:
    desc: Build Go binary with embedded client
    deps: [build:client]
    dir: '{{.SERVER_DIR}}'
    cmds:
      - mkdir -p ../{{.DIST_DIR}}
      - go build -o ../{{.DIST_DIR}}/vtt-remote .
    sources:
      - '{{.SERVER_DIR}}/**/*.go'
      - '{{.SERVER_DIR}}/go.mod'
      - '{{.SERVER_DIR}}/go.sum'
    generates:
      - '{{.DIST_DIR}}/vtt-remote'

  dev:server:
    desc: Run server in development mode (PORT=8181 task dev:server)
    deps: [build:client]
    dir: '{{.SERVER_DIR}}'
    vars:
      PORT: '{{.PORT | default "8080"}}'
    cmds:
      - go run . -port {{.PORT}}

  test:server:
    desc: Run Go server tests
    dir: '{{.SERVER_DIR}}'
    cmds:
      - go test -v -race ./...

  # ================================
  # Desktop App (Wails)
  # ================================

  install:wails:
    desc: Install Wails CLI
    cmds:
      - go install github.com/wailsapp/wails/v2/cmd/wails@latest
    status:
      - which wails

  install:desktop:
    desc: Install desktop frontend npm dependencies
    dir: '{{.DESKTOP_DIR}}/frontend'
    cmds:
      - npm install
    sources:
      - '{{.DESKTOP_DIR}}/frontend/package.json'
      - '{{.DESKTOP_DIR}}/frontend/package-lock.json'
    generates:
      - '{{.DESKTOP_DIR}}/frontend/node_modules/.package-lock.json'

  build:desktop:
    desc: Build desktop app for current platform
    deps: [install:wails, install:desktop, build:module]
    dir: '{{.DESKTOP_DIR}}'
    cmds:
      - mkdir -p phone-client
      - cmd: cp -r ../{{.CLIENT_DIR}}/dist/* phone-client/
        ignore_error: true
      - '{{.WAILS}} build'
      - mkdir -p ../{{.DIST_DIR}}
      - cp -r build/bin/* ../{{.DIST_DIR}}/
    sources:
      - '{{.DESKTOP_DIR}}/*.go'
      - '{{.DESKTOP_DIR}}/frontend/src/**/*'
      - '{{.DESKTOP_DIR}}/wails.json'
    generates:
      - '{{.DIST_DIR}}/VTT Remote*'

  build:desktop:darwin:
    desc: Build desktop app for macOS (universal)
    deps: [install:wails, install:desktop, build:module, build:client]
    dir: '{{.DESKTOP_DIR}}'
    cmds:
      - mkdir -p phone-client
      - cp -r ../{{.CLIENT_DIR}}/dist/* phone-client/
      - '{{.WAILS}} build -platform darwin/universal'
      - cp -r build/bin/* ../{{.DIST_DIR}}/

  build:desktop:windows:
    desc: Build desktop app for Windows
    deps: [install:wails, install:desktop, build:module, build:client]
    dir: '{{.DESKTOP_DIR}}'
    cmds:
      - mkdir -p phone-client
      - cp -r ../{{.CLIENT_DIR}}/dist/* phone-client/
      - '{{.WAILS}} build -platform windows/amd64'
      - cp -r build/bin/* ../{{.DIST_DIR}}/

  dev:desktop:
    desc: Run desktop app in development mode
    deps: [install:wails, install:desktop]
    dir: '{{.DESKTOP_DIR}}'
    cmds:
      - mkdir -p phone-client
      - cmd: cp -r ../{{.CLIENT_DIR}}/dist/* phone-client/
        ignore_error: true
      - '{{.WAILS}} dev'

  test:desktop:
    desc: Run desktop Go tests
    dir: '{{.DESKTOP_DIR}}'
    cmds:
      - go test -v -race ./...

  test:relay:
    desc: Run relay package tests
    dir: pkg/relay
    cmds:
      - go test -v -race ./...

  test:all:
    desc: Run all tests (server, relay, desktop)
    cmds:
      - task: test:relay
      - task: test:server
      - task: test:desktop
      - task: test:module

  # ================================
  # Foundry Module
  # ================================

  install:module:
    desc: Install Foundry module npm dependencies
    dir: '{{.MODULE_DIR}}'
    cmds:
      - npm install
    sources:
      - '{{.MODULE_DIR}}/package.json'
      - '{{.MODULE_DIR}}/package-lock.json'
    generates:
      - '{{.MODULE_DIR}}/node_modules/.package-lock.json'

  build:module:
    desc: Build Foundry VTT module
    dir: '{{.MODULE_DIR}}'
    deps: [install:module]
    cmds:
      - npm run build
      - mkdir -p ../{{.DIST_DIR}}/foundry-module
      - cp module.json ../{{.DIST_DIR}}/foundry-module/
      - cp -r dist/* ../{{.DIST_DIR}}/foundry-module/
      - cp -r styles ../{{.DIST_DIR}}/foundry-module/
      - cp -r languages ../{{.DIST_DIR}}/foundry-module/
      - cp -r templates ../{{.DIST_DIR}}/foundry-module/ 2>/dev/null || true
    sources:
      - '{{.MODULE_DIR}}/src/**/*'
      - '{{.MODULE_DIR}}/styles/**/*'
      - '{{.MODULE_DIR}}/languages/**/*'
      - '{{.MODULE_DIR}}/module.json'
    generates:
      - '{{.DIST_DIR}}/foundry-module/**/*'

  dev:module:
    desc: Watch source files, rebuild and copy to Foundry on changes
    deps: [copy:module]
    dir: '{{.MODULE_DIR}}'
    vars:
      MODULE_DEST: '~/Library/Application Support/FoundryVTT/Data/modules/vtt-remote'
    cmds:
      - |
        echo "👀 Watching for changes... (Ctrl+C to stop)"
        npx chokidar "src/**/*" "styles/**/*" "languages/**/*" "templates/**/*" "module.json" -c "task copy:module"

  copy:module:
    desc: Build and copy module to Foundry (one-shot)
    deps: [build:module]
    vars:
      MODULE_DEST: '~/Library/Application Support/FoundryVTT/Data/modules/vtt-remote'
    cmds:
      - |
        DEST=$(eval echo "{{.MODULE_DEST}}")
        rm -rf "$DEST"
        cp -R "{{.DIST_DIR}}/foundry-module" "$DEST"
        echo "✓ Copied module to $DEST"

  package:module:
    desc: Create distributable module zip
    deps: [build:module]
    dir: '{{.DIST_DIR}}'
    cmds:
      - zip -r vtt-remote-module.zip foundry-module
    generates:
      - '{{.DIST_DIR}}/vtt-remote-module.zip'

  # ================================
  # Quality Checks
  # ================================

  test:module:
    desc: Run Foundry module unit tests
    dir: '{{.MODULE_DIR}}'
    deps: [install:module]
    cmds:
      - npm run test

  test:module:watch:
    desc: Run Foundry module tests in watch mode
    dir: '{{.MODULE_DIR}}'
    deps: [install:module]
    cmds:
      - npm run test:watch

  typecheck:
    desc: Type check Foundry module
    dir: '{{.MODULE_DIR}}'
    deps: [install:module]
    cmds:
      - npm run typecheck

  lint:
    desc: Lint all code (Go + TypeScript)
    cmds:
      - task: lint:go
      - task: lint:ts

  lint:go:
    desc: Lint Go code with golangci-lint
    dir: '{{.SERVER_DIR}}'
    cmds:
      - golangci-lint run ./...

  lint:ts:
    desc: Lint TypeScript/JavaScript code
    dir: '{{.MODULE_DIR}}'
    deps: [install:module]
    cmds:
      - npm run lint

  # ================================
  # Utilities
  # ================================

  link:module:
    desc: Symlink built module to local Foundry installation
    deps: [build:module]
    vars:
      MODULE_DEST: '{{.FOUNDRY_DATA}}/modules/vtt-remote'
    cmds:
      - |
        DEST=$(eval echo "{{.MODULE_DEST}}")
        if [ -L "$DEST" ]; then
          echo "Removing existing symlink..."
          rm "$DEST"
        elif [ -d "$DEST" ]; then
          echo "Error: $DEST exists and is not a symlink. Remove it manually."
          exit 1
        fi
        ln -s "$(pwd)/{{.DIST_DIR}}/foundry-module" "$DEST"
        echo "✓ Linked to $DEST"
    status:
      - test -L "$(eval echo '{{.MODULE_DEST}}')"

  unlink:module:
    desc: Remove module symlink from Foundry
    vars:
      MODULE_DEST: '{{.FOUNDRY_DATA}}/modules/vtt-remote'
    cmds:
      - |
        DEST=$(eval echo "{{.MODULE_DEST}}")
        if [ -L "$DEST" ]; then
          rm "$DEST"
          echo "✓ Removed symlink"
        else
          echo "No symlink found at $DEST"
        fi

  clean:
    desc: Remove all build artifacts
    cmds:
      - rm -rf {{.DIST_DIR}}
      - rm -rf {{.MODULE_DIR}}/dist
      - rm -rf {{.MODULE_DIR}}/node_modules
      - rm -rf {{.SERVER_DIR}}/public/*
      - touch {{.SERVER_DIR}}/public/.keep

  # ================================
  # Documentation (MkDocs)
  # ================================

  docs:serve:
    desc: Serve docs locally with live reload
    dir: '{{.DOCS_DIR}}'
    cmds:
      - uv run --with mkdocs-material --with mkdocs-minify-plugin mkdocs serve

  docs:build:
    desc: Build static documentation site
    dir: '{{.DOCS_DIR}}'
    cmds:
      - uv run --with mkdocs-material --with mkdocs-minify-plugin mkdocs build
    sources:
      - '{{.DOCS_DIR}}/mkdocs.yml'
      - '{{.DOCS_DIR}}/docs/**/*'
    generates:
      - '{{.DOCS_DIR}}/site/**/*'

  # ================================
  # Release & Deployment
  # ================================

  release:
    desc: "Bump version and trigger deploy (VERSION=patch|minor|major|x.y.z)"
    vars:
      VERSION: '{{.VERSION | default "patch"}}'
      MODULE_JSON: '{{.MODULE_DIR}}/module.json'
    cmds:
      - |
        CURRENT=$(jq -r '.version' {{.MODULE_JSON}})
        echo "Current version: $CURRENT"

        # Parse current version
        IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"

        # Calculate new version
        case "{{.VERSION}}" in
          patch)
            NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))"
            ;;
          minor)
            NEW_VERSION="$MAJOR.$((MINOR + 1)).0"
            ;;
          major)
            NEW_VERSION="$((MAJOR + 1)).0.0"
            ;;
          *)
            # Assume explicit version provided
            NEW_VERSION="{{.VERSION}}"
            ;;
        esac

        echo "New version: $NEW_VERSION"

        # Update module.json
        jq --arg v "$NEW_VERSION" '.version = $v' {{.MODULE_JSON}} > /tmp/module.json.tmp
        mv /tmp/module.json.tmp {{.MODULE_JSON}}

        # Commit and push
        git add {{.MODULE_JSON}}
        git commit -m "chore: release v$NEW_VERSION"
        git push

        echo "✅ Released v$NEW_VERSION - GitHub Actions will deploy automatically"

  deploy:
    desc: Deploy to production server (configure via deploy/.env or DEPLOY_HOST env var)
    dotenv: ['deploy/.env']
    cmds:
      - |
        DEPLOY_HOST="${DEPLOY_HOST:-user@your-server.example.com}"
        DEPLOY_PATH="${DEPLOY_PATH:-/opt/vtt-remote}"
        if [ "$DEPLOY_HOST" = "user@your-server.example.com" ]; then
          echo "Error: Configure deploy target in deploy/.env or set DEPLOY_HOST env var"
          echo "  Run: uv run scripts/setup-env.py"
          exit 1
        fi
        echo "📦 Syncing files to $DEPLOY_HOST..."
        rsync -avz --exclude='.git' --exclude='node_modules' --exclude='dist' --exclude='.claude' . "$DEPLOY_HOST:$DEPLOY_PATH/"
        echo "🐳 Building and restarting containers..."
        ssh "$DEPLOY_HOST" "cd $DEPLOY_PATH/deploy && docker compose --profile traefik build && docker compose --profile traefik up -d"
        echo "✅ Verifying deployment..."
        sleep 3
        ssh "$DEPLOY_HOST" 'curl -sf http://localhost:8080/health && echo " - Server healthy!"'
