#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""
Interactive setup script for VTT Remote .env configuration.
Run with: uv run scripts/setup-env.py
"""

import os
import re
from pathlib import Path


def prompt(question: str, default: str = "") -> str:
    """Prompt user for input with optional default value."""
    if default:
        user_input = input(f"{question} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        while True:
            user_input = input(f"{question}: ").strip()
            if user_input:
                return user_input
            print("  This field is required.")


def validate_domain(domain: str) -> bool:
    """Basic domain validation."""
    pattern = r"^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z]{2,})+$"
    return bool(re.match(pattern, domain))


def validate_email(email: str) -> bool:
    """Basic email validation."""
    pattern = r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
    return bool(re.match(pattern, email))


def prompt_domain(question: str, default: str = "") -> str:
    """Prompt for a domain with validation."""
    while True:
        value = prompt(question, default)
        if validate_domain(value):
            return value
        print(f"  '{value}' doesn't look like a valid domain. Try again.")


def prompt_email(question: str, default: str = "") -> str:
    """Prompt for an email with validation."""
    while True:
        value = prompt(question, default)
        if validate_email(value):
            return value
        print(f"  '{value}' doesn't look like a valid email. Try again.")


def main():
    print("\n" + "=" * 60)
    print("  VTT Remote - Environment Setup")
    print("=" * 60)
    print("\nThis script will help you configure your .env file.")
    print("Press Ctrl+C to abort at any time.\n")

    # Collect configuration
    config = {}

    print("─" * 40)
    print("Domain Configuration")
    print("─" * 40)

    config["VTT_DOMAIN"] = prompt_domain(
        "Relay server domain (e.g., vtt-remote.yourdomain.com)",
        default="",
    )

    config["DOCS_DOMAIN"] = prompt_domain(
        "Documentation domain (e.g., docs.yourdomain.com)",
        default=f"docs.{config['VTT_DOMAIN'].split('.', 1)[-1] if '.' in config['VTT_DOMAIN'] else config['VTT_DOMAIN']}",
    )

    print("\n" + "─" * 40)
    print("SSL Certificate (Let's Encrypt)")
    print("─" * 40)

    config["ACME_EMAIL"] = prompt_email(
        "Email for Let's Encrypt notifications",
        default="",
    )

    print("\n" + "─" * 40)
    print("Deployment Target")
    print("─" * 40)

    config["DEPLOY_HOST"] = prompt(
        "Deploy target (user@host)",
        default="",
    )

    config["DEPLOY_PATH"] = prompt(
        "Remote deploy path",
        default="/opt/vtt-remote",
    )

    # Generate .env content
    env_content = f"""# VTT Remote - Environment Configuration
# Generated by setup-env.py

# Domain for the relay server SSL certificate (used with Traefik)
VTT_DOMAIN={config['VTT_DOMAIN']}

# Domain for documentation site
DOCS_DOMAIN={config['DOCS_DOMAIN']}

# Email for Let's Encrypt notifications
ACME_EMAIL={config['ACME_EMAIL']}

# Deployment target (user@host)
DEPLOY_HOST={config['DEPLOY_HOST']}

# Remote path for deployment
DEPLOY_PATH={config['DEPLOY_PATH']}
"""

    # Preview
    print("\n" + "=" * 60)
    print("  Configuration Preview")
    print("=" * 60)
    for key, value in config.items():
        print(f"  {key}={value}")

    # Determine output path
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    deploy_dir = project_root / "deploy"
    env_path = deploy_dir / ".env"

    print(f"\nOutput file: {env_path}")

    # Check for existing file
    if env_path.exists():
        overwrite = input("\n.env file already exists. Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("Aborted. No changes made.")
            return

    # Write file
    env_path.write_text(env_content)
    print(f"\n✓ Configuration saved to {env_path}")
    print("\nNext steps:")
    print("  1. Review the generated .env file")
    print("  2. Run 'task deploy' to deploy the server")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nAborted by user.")
