// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function DetectFoundryPath() {
  return window['go']['main']['App']['DetectFoundryPath']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetModuleStatus(arg1) {
  return window['go']['main']['App']['GetModuleStatus'](arg1);
}

export function GetServerURL() {
  return window['go']['main']['App']['GetServerURL']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function InstallModule(arg1) {
  return window['go']['main']['App']['InstallModule'](arg1);
}

export function SetPort(arg1) {
  return window['go']['main']['App']['SetPort'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
