// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearLogs():Promise<void>;

export function DetectFoundryPath():Promise<string>;

export function GetLogs():Promise<Array<main.LogEntry>>;

export function GetModuleStatus(arg1:string):Promise<main.FoundryModuleStatus>;

export function GetServerURL():Promise<string>;

export function GetStats():Promise<main.ClientStats>;

export function GetStatus():Promise<main.ServerStatus>;

export function InstallModule(arg1:string):Promise<void>;

export function SetPort(arg1:number):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;
